### PR TITLE
Ci/setup ci

### PR DESCRIPTION
**Pull request by ad2ien**
Make this forked project able to build a docker image and push it to ghcr.
Additionally and some linters and make then happy.

### CODE REVIEW

**Review by hleonardtek — APPROVED** [review]
Looks alright !

**Review by amimart — CHANGES_REQUESTED** [review]
I think the `Release` workflow is missing

**Review by ccamel — APPROVED** [review]
Great! :+1:

**Comment by ad2ien** [comment]
Hi @amimart, I added the release workflow

**Review by amimart — APPROVED** [review]

**Pull request merged**
